//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class aaJobStep
    {
        public int id { get; set; }
        public string description { get; set; }
        public string warning { get; set; }
        public string caution { get; set; }
        public string note { get; set; }
        public string photo { get; set; }
        public Nullable<int> wiid { get; set; }
        public Nullable<bool> barrier { get; set; }
    }
}
