//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApi2
{
    using System;
    using System.Collections.Generic;
    
    public partial class aaWi
    {
        public int id { get; set; }
        public string jobTitle { get; set; }
        public string facility { get; set; }
        public string status { get; set; }
        public string generalPrecaution { get; set; }
        public Nullable<int> equipmentType { get; set; }
        public Nullable<int> equipmentMake { get; set; }
        public string localPrecaution { get; set; }
        public string wiNo { get; set; }
    }
}
