//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class a1
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Nullable<int> pId { get; set; }
    
        public virtual a0 a0 { get; set; }
    }
}
