//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class atw
    {
        public string BU { get; set; }
        public string Unit { get; set; }
        public string Status { get; set; }
        public string trircountC { get; set; }
        public Nullable<int> trircountBest { get; set; }
        public string ltircountC { get; set; }
        public Nullable<int> ltircountBest { get; set; }
        public string hiPocountC { get; set; }
        public Nullable<int> hiPocountBest { get; set; }
        public string DroppedObjectC { get; set; }
        public Nullable<int> DroppedObjectBest { get; set; }
        public string HiPoDroppedObjectC { get; set; }
        public Nullable<int> HiPoDroppedObjectBest { get; set; }
        public string RecordableHandInjuryC { get; set; }
        public Nullable<int> RecordableHandInjuryBest { get; set; }
        public string HandInjuryC { get; set; }
        public Nullable<int> HandInjuryBest { get; set; }
        public string HarmToPeopleC { get; set; }
        public Nullable<int> HarmToPeopleBest { get; set; }
        public string DischargeVolumeC { get; set; }
        public Nullable<int> DischargeVolumeBest { get; set; }
        public byte[] r { get; set; }
        public Nullable<int> id { get; set; }
    }
}
